"""
detector.py — Two independent AI-detection signals for Provenance Guard.

Signal 1 (LLM): Groq llama-3.3-70b-versatile classifies the text semantically.
Signal 2 (Stylometric): Pure-Python heuristics measure statistical writing properties.
"""

import os
import re
import json
import math
from groq import Groq
from dotenv import load_dotenv

load_dotenv()


# ---------------------------------------------------------------------------
# Signal 1: LLM-based classifier (Groq)
# ---------------------------------------------------------------------------

def _groq_signal(text: str) -> dict:
    """Ask an LLM to assess whether the text reads as human or AI-generated."""
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    prompt = f"""You are an expert at distinguishing human-written text from AI-generated text.

Analyze the text below and determine whether it was written by a human or generated by an AI.

Text:
\"\"\"
{text}
\"\"\"

Respond with a JSON object containing exactly these fields:
- "prediction": "human" or "ai"
- "confidence": a float from 0.0 to 1.0 representing your certainty
- "reasoning": one or two sentences explaining your conclusion

Reply ONLY with the JSON object."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        response_format={"type": "json_object"},
    )

    result = json.loads(response.choices[0].message.content)
    return {
        "signal": "llm_classifier",
        "prediction": result.get("prediction", "unknown"),
        "confidence": float(result.get("confidence", 0.5)),
        "reasoning": result.get("reasoning", ""),
    }


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

def _stylometric_signal(text: str) -> dict:
    """
    Measure statistical properties that differ between human and AI writing.

    Metrics:
      - Sentence-length standard deviation: AI text is more uniform; humans vary.
      - Type-token ratio (TTR): vocabulary diversity score.
      - Punctuation density: humans use more varied punctuation marks.
      - Average word length: minor signal; AI slightly favours longer words.
    """
    # Split into sentences and words
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    words = re.findall(r"\b\w+\b", text.lower())

    if not words:
        return {
            "signal": "stylometric",
            "prediction": "unknown",
            "confidence": 0.5,
            "metrics": {},
            "reasoning": "Insufficient text for analysis.",
        }

    # --- Metric 1: sentence-length standard deviation ---
    if len(sentences) > 1:
        lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
        mean_len = sum(lengths) / len(lengths)
        variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
        sent_std = math.sqrt(variance)
    else:
        sent_std = 0.0

    # --- Metric 2: type-token ratio ---
    ttr = len(set(words)) / len(words)

    # --- Metric 3: punctuation density ---
    punct_hits = re.findall(r"[,;:—\-–\(\)\[\]\"\'!?]", text)
    punct_density = len(punct_hits) / len(words)

    # --- Metric 4: average word length ---
    avg_word_len = sum(len(w) for w in words) / len(words)

    # --- Scoring (higher score = more human-like) ---
    score = 0.0
    reasons = []

    # Sentence variance
    if sent_std >= 8:
        score += 0.35
        reasons.append(f"high sentence-length variance (σ={sent_std:.1f})")
    elif sent_std >= 4:
        score += 0.15
        reasons.append(f"moderate sentence-length variance (σ={sent_std:.1f})")
    else:
        reasons.append(f"low sentence-length variance (σ={sent_std:.1f}) — typical of AI")

    # Vocabulary diversity
    if ttr >= 0.60:
        score += 0.25
        reasons.append(f"diverse vocabulary (TTR={ttr:.2f})")
    elif ttr >= 0.45:
        score += 0.10
        reasons.append(f"moderate vocabulary diversity (TTR={ttr:.2f})")
    else:
        reasons.append(f"repetitive vocabulary (TTR={ttr:.2f}) — typical of AI")

    # Punctuation richness
    if punct_density >= 0.08:
        score += 0.25
        reasons.append(f"rich punctuation (density={punct_density:.2f})")
    elif punct_density >= 0.04:
        score += 0.10
        reasons.append(f"moderate punctuation (density={punct_density:.2f})")
    else:
        reasons.append(f"sparse punctuation (density={punct_density:.2f}) — typical of AI")

    # Word length (minor)
    if avg_word_len <= 4.8:
        score += 0.15
        reasons.append(f"shorter avg word length ({avg_word_len:.1f}) — more conversational")
    else:
        reasons.append(f"longer avg word length ({avg_word_len:.1f}) — slightly formal")

    # Verdict
    prediction = "human" if score >= 0.45 else "ai"
    # Map score to confidence: clamp to [0.50, 0.95]
    raw_conf = score if prediction == "human" else (1.0 - score)
    confidence = round(max(0.50, min(0.95, raw_conf + 0.20)), 3)

    return {
        "signal": "stylometric",
        "prediction": prediction,
        "confidence": confidence,
        "metrics": {
            "sentence_length_std_dev": round(sent_std, 2),
            "type_token_ratio": round(ttr, 3),
            "punctuation_density": round(punct_density, 3),
            "avg_word_length": round(avg_word_len, 2),
        },
        "reasoning": "; ".join(reasons),
    }


# ---------------------------------------------------------------------------
# Ensemble: combine both signals into a final verdict
# ---------------------------------------------------------------------------

def analyze_text(text: str) -> dict:
    """
    Run both detection signals and return a weighted ensemble verdict.

    Weights: LLM 60% + Stylometric 40%
    (LLM captures semantic coherence; stylometrics capture surface statistics.)
    """
    llm = _groq_signal(text)
    style = _stylometric_signal(text)

    # Convert each signal's confidence into a "human probability" in [0, 1]
    llm_human_p = llm["confidence"] if llm["prediction"] == "human" else 1.0 - llm["confidence"]
    sty_human_p = style["confidence"] if style["prediction"] == "human" else 1.0 - style["confidence"]

    combined = 0.60 * llm_human_p + 0.40 * sty_human_p
    final_prediction = "human" if combined >= 0.50 else "ai"
    final_confidence = combined if final_prediction == "human" else 1.0 - combined

    return {
        "prediction": final_prediction,
        "confidence": round(final_confidence, 3),
        "signals": [llm, style],
        "text_length": len(text),
    }
